version: "3.9"
services:
  reverse_apache:
    build: ./reverse_apache/
  default_backend_apache:
    build: ./default_backend_apache/
  backend_nginx:
    build: ./backend_nginx/
  reverse_nginx:
    build: ./reverse_nginx/
    ports:
      - "8082:8082"
  gunicorn:
    build: ./gunicorn/